adminuser/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views

app_name = 'adminuser'

urlpatterns = [
    # path('index/', views.index, name="index"),
    path('register/', views.register, name='register'),
    path('login', views.admin_login, name='login'),
    path('update', views.admin_update, name='update'),
    path('navi_statistics', views.navi_statistics, name='navi_statistics'),
    path('statistics', views.statistics, name='statistics'),
    path('not_clockin_rank', views.not_clockin_rank, name='not_clockin_rank'),
    path('export_excel', views.export_excel, name='export_excel')
]

djangoProject/urls.py
import notifications.urls
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

import login.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('clockin/', include('clockin.urls')),
    path('adminuser/', include('adminuser.urls')),
    re_path(r'^password_reset/', include('password_reset.urls')),
    path('inbox/notifications', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('captcha', include('captcha.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = login.views.page_not_found_error
handler500 = login.views.page_error

login/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *
from . import views

app_name = 'login'

urlpatterns = [
    path('index/', views.index, name="index"),
    path("register/", views.register, name="register"),
    path('user_detail/', views.user_detail, name="user_detail"),
    path('user_update/', views.user_update, name="user_update"),
    path('user_login/', views.user_login, name="user_login"),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('user_delete/<str:user_uuid>', views.user_delete, name='user_delete'),
    re_path('^user_update/get_all_org/', views.get_all_org, name='get_all_org'),
    path('is_have_email', views.is_have_email, name='is_have_email'),
    path('check_pwd', views.check_pwd, name='check_pwd'),
    path('user_login/pc_get_captcha', views.pc_get_captcha, name='pc_get_captcha'),
    path('register/pc_get_captcha', views.pc_get_captcha, name='pc_get_captcha'),
    path('page_not_found_error', views.page_not_found_error, name='page_not_found_error'),
    path('page_error', views.page_error, name='page_error')
]

adminuser/models.py
from django.db import models


# Create your models here.

class Admin(models.Model):
    admin_id = models.CharField(max_length=255, blank=True, null=True)
    admin_name = models.CharField(max_length=255, blank=True, null=True)
    admin_org = models.CharField(max_length=255, blank=True, null=True, unique=True)
    admin_level = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'admin'

    def __str__(self):
        return self.admin_name


class Org(models.Model):
    org_id = models.CharField(max_length=255, blank=True, null=True)
    org_name = models.CharField(unique=True, max_length=255, blank=True, null=True)
    org_designate_location = models.CharField(max_length=255, blank=True, null=True)
    strategy_time = models.TimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'org'

    def __str__(self):
        return self.org_name + " " + str(self.strategy_time)

adminuser/forms.py
from django import forms

from .models import Admin
from login.models import User


class AdminLoginForm(forms.Form):
    email = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = User
        fields = ('email', 'password')


class AdminUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('user_name', 'user_org', 'user_bind_num', 'phone', 'email', 'profile_photo')


class AdminRegisterForm(forms.ModelForm):
    # 复写 User 的密码
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ("password", "user_uuid", "email", 'user_name', "user_org")

    # 对两次输入的密码是否一致进行检查
    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError("密码输入不一致,请重试。")

adminuser/views.py
import datetime, json, os, time, uuid
from django.template import loader
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, StreamingHttpResponse
from django.utils.datastructures import MultiValueDictKeyError
from login.models import User
from .models import Admin, Org
from clockin.models import Record
from .forms import AdminRegisterForm, AdminUpdateForm, AdminLoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.conf import settings
from notifications.signals import notify
from apscheduler.scheduler import Scheduler
from functools import cmp_to_key
from django.views.decorators.clickjacking import xframe_options_sameorigin
from pyecharts.globals import CurrentConfig, ThemeType
from pyecharts import options as opts
from pyecharts.charts import Pie
from django.contrib import messages
from notifications.models import Notification
from xlwt import Workbook
from io import BytesIO


@xframe_options_sameorigin
@login_required(login_url='/login/user_login/')
def statistics(request):
    org = User.objects.get(user_uuid=request.session['user_uuid']).user_org
    org_people_num = User.objects.exclude(is_superuser=1).filter(user_org=org).count()
    org_people = User.objects.filter(user_org=org)
    statis_type = request.GET.get('type')
    exact_figure, cut_num = 0, 0
    anticipate_figure = 0
    title = ""
    if statis_type == 'day':
        anticipate_figure = org_people_num
        cut_num = 1
        title = "日"
    elif statis_type == 'week':
        anticipate_figure = 7 * org_people_num
        cut_num = 7
        title = "周"
    elif statis_type == 'month':
        anticipate_figure = 30 * org_people_num
        cut_num = 30
        title = "月"
    day = datetime.datetime.now()
    for p in org_people:
        exact = Record.objects.filter(user_id=p.user_uuid).all().order_by('-create_time')[:cut_num]
        exact_figure += len(exact)
    pie = (
        Pie(init_opts=opts.InitOpts(theme=ThemeType.LIGHT)).add("", list(zip(['已打卡', '未打卡'],
                                                                             [exact_figure,
                                                                              anticipate_figure - exact_figure])))
            .set_global_opts(title_opts=opts.TitleOpts()).set_series_opts(
            label_opts=opts.LabelOpts(formatter="{b}:{c}\n({d}%)"))
    )
    data = {'data': pie.render_embed()}
    return render(request, 'chart.html', data)


def navi_statistics(request):
    return render(request, 'adminuser/statistics.html')


# Create your views here.
def register(request):
    # 不是超级管理员 不允许进入创建管理员界面
    if request.session['admin_level'] is None or request.session['admin_level'] != 1:
        return redirect("login:index")
    # 判断用户是否提交数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        user_register_form = AdminRegisterForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.is_superuser = 1;
            # 随机生成uuid
            new_user.user_uuid = uuid.uuid1()
            new_user.save()
            new_user = authenticate(email=new_user.email, password=user_register_form.cleaned_data['password'])
            admin = Admin()
            admin.admin_name = new_user.user_name
            admin.admin_id = new_user.user_uuid
            admin.admin_level = 2
            admin.admin_org = new_user.user_org
            admin.save()
            login(request, new_user)
            request.session['user_uuid'] = new_user.user_uuid
            request.session['admin_level'] = admin.admin_level
            return redirect("login:index")
        # 如果数据不合法，返回错误信息
        else:
            print(user_register_form.errors)
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    elif request.method == 'GET':
        # 创建表单类实例
        user_register_form = AdminRegisterForm()
        # 赋值上下文
        context = {'user_form': user_register_form}
        # 返回模板
        return render(request, 'adminuser/register.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


def admin_login(request):
    if request.method == 'POST':
        user_form = AdminLoginForm(data=request.POST)
        if user_form.is_valid():
            data = user_form.cleaned_data
            user = authenticate(email=data['email'], password=data['password'])
            if user:
                if user.is_superuser == 0:
                    messages.error(request, '没有此管理员')
                    return redirect('login:user_login')
                admin = Admin.objects.get(admin_id=user.user_uuid)
                request.session['user_uuid'] = user.user_uuid
                request.session['admin_level'] = admin.admin_level
                if admin.admin_level > 1:
                    if Org.objects.get(org_name=admin.admin_org).strategy_time is not None and Org.objects.get(
                            org_name=admin.admin_org).strategy_time != '':
                        request.session['strategy_time'] = str(Org.objects.get(org_name=admin.admin_org).strategy_time)
                        print(request.session['strategy_time'])
                    else:
                        request.session['strategy_time'] = ''
                login(request, user)
                return redirect("login:index")
            else:
                messages.error(request, '账号或密码输入有误，请重新输入')
                return redirect('login:user_login')
        else:
            messages.error(request, '账号或密码输入不合法')
            return redirect('login:user_login')
    elif request.method == 'GET':
        user_form = AdminLoginForm()
        context = {'user_form': user_form}
        return render(request, 'user/login.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


@login_required(login_url='/login/user_login/')
def admin_update(request):
    user = User.objects.get(user_uuid=request.session['user_uuid'])
    admin = Admin.objects.get(admin_id=request.session['user_uuid'])
    photo = user.profile_photo.path
    # 判断用户是否提交数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        user_form = AdminUpdateForm(request.POST, request.FILES, instance=user)
        # 判断提交的数据是否满足模型的要求
        if user_form.is_valid():
            user.user_name = request.POST['user_name']
            user.user_org = request.POST['user_org']
            if request.POST['phone'] == '' or request.POST['phone'] is None:
                user.phone = None
            else:
                user.phone = request.POST['phone']
            user.email = request.POST['email']
            user.user_bind_num = request.POST['user_bind_num']
            try:
                user.gender = request.POST['gender']
            except MultiValueDictKeyError:
                user.gender = 2
            if 'profile_photo' in request.FILES:
                if photo != settings.MEDIA_ROOT + "default.png":
                    os.remove(photo)
                user.profile_photo = request.FILES['profile_photo']
            # if request.POST['strategy_time'] == '' or request.POST['strategy_time'] is None:
            # admin.
            user.save()
            org = Org.objects.get(org_name=admin.admin_org)

            if request.POST['strategy_time'] is not None and request.POST['strategy_time'] != '':
                org.strategy_time = request.POST['strategy_time']
                request.session['strategy_time'] = org.strategy_time
            else:
                request.session['strategy_time'] = ''

            org.save()
            # 完成后返回到用户明细
            return redirect("login:user_detail")
        # 如果数据不合法，返回错误信息
        else:
            print(user_form.errors)
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    else:
        # 创建表单类实例
        user_update_form = AdminUpdateForm()
        # 赋值上下文
        context = {'user': user, 'user_update_form': user_update_form}
        # 返回模板
        return render(request, 'user/update.html', context)


# 实例化定时任务
sched = Scheduler()


# 每日自动打卡提醒
@sched.interval_schedule(minutes=1, coalesce=False)
def remind_clockin():
    now = datetime.datetime.now()
    cur = datetime.datetime.strftime(now, "%H:%M")
    day = datetime.datetime.strftime(now, "%Y-%m-%d")
    orgs = list(Org.objects.exclude(strategy_time=None).filter(strategy_time=cur))
    print(orgs)
    if len(orgs) == 0:
        return
    for org in orgs:
        admin = Admin.objects.get(admin_org=org.org_name)
        users = list(User.objects.exclude(user_uuid=admin.admin_id).filter(user_org=admin.admin_org))
        for user in users:
            if Record.objects.filter(user_id=user.user_uuid).filter(create_time=day).count() == 0:
                print(user)
                notify.send(admin, recipient=user, verb='通知你该打卡了')

        print(users)

    print("_____________________test_____________________")
    # admins = Admin.objects.exclude(admin_level=1).all().first()
    # print(admins)
    # user = User.objects.get(user_id=3)
    # notify.send(admins, recipient=user, verb='通知你该打卡了')


sched.start()

excel_user = []


@login_required(login_url='/login/user_login/')
def not_clockin_rank(request):
    admin = Admin.objects.filter(admin_id=request.session['user_uuid']).first()
    org = admin.admin_org
    users = User.objects.filter(user_org=org).all()
    global excel_user
    excel_user = users
    rank = []
    for u in users:
        cnt = Notification.objects.filter(recipient_id=u.user_id)[:30].count()
        if cnt > 0:
            rank.append({'user': {'user_bind_num': u.user_bind_num, 'email': u.email, 'phone': u.phone,
                                  'realname': u.realname}, 'cnt': cnt})
    rank = {'data': rank}
    return JsonResponse(rank)

templates/adminuser/register.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    注册
{% endblock %}
{% block content %}

    <link href="{% static 'css/IntelliSense.css' %}" type="text/css" rel="stylesheet"/>
    <link href="{% static 'css/cropper.min.css' %}" type="text/css" rel="stylesheet"/>
    <script src="{% static 'js/IntelliSense.js' %}"></script>
    <script src="{% static 'js/cropper.min.js' %}"></script>
    {# 单位/学校智能输入提示 #}
    <script>
        $(document).ready(function () {
            //$('#user_org').val(api);
            createApi();
        });

        var autoComplete;

        function createApi() {
            var inputValue = []
            $.getJSON("{% url 'login:get_all_org' %}", function (org) {
                $.each(org, function (k, v) {
                    inputValue.push(v['fields']['org_name'])
                })
            })
            console.log(inputValue)

            if (!autoComplete) {
                autoComplete = new AutoComplete('user_org', 'auto', inputValue);//第一个参数是输入框id，第二个是下拉显示的id，第三个是获取的全部数据。
            }
            $('#user_org').blur(function () {//点击下拉选项得到获取值
                //alert($('#user_org').val());点击获取选择的值。
            });
        }
    </script>
    <script>
        //判断是否重复邮箱
        function isHaveEmail() {
            $.ajax({
                url: '{% url 'login:is_have_email' %}',
                type: 'POST',
                data: {'email': $('#email').val()},
                dataType: 'json',
                success: function (msg) {
                    json = eval(msg)
                    if (json.result == "False") {
                        $('#email').addClass('is-invalid')
                    } else {
                        $('#email').removeClass('is-invalid')
                    }
                }
            })
        }

        function checkPWD() {
            $.ajax({
                url: '{% url 'login:check_pwd' %}',
                type: 'POST',
                data: {'pwd1': $('#password').val(), 'pwd2': $('#password2').val()},
                dataType: 'json',
                success: function (msg) {
                    json = eval(msg)
                    if (json.result == "False") {
                        $('#password').addClass('is-invalid')
                        $('#password2').addClass('is-invalid')
                    } else {
                        $('#password').removeClass('is-invalid')
                        $('#password2').removeClass('is-invalid')
                    }
                }
            })
        }
    </script>
    <div class="container">
        <div class="row card border-light" style="background: transparent">
            <div class="col-4 card-body m-auto">
                <br/>
                <form method="post" action="{% url 'adminuser:register' %}">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="user_name" name="user_name" placeholder="用户名"
                               required>
                        <label for="user_name">用户名</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com"
                               aria-describedby="emailFeedback" required onkeyup="isHaveEmail()">
                        <label for="email" id="email_label">邮箱</label>
                        <div id="emailFeedback" class="invalid-feedback">
                            该邮箱已被注册
                        </div>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="user_org" name="user_org" autocomplete="off" placeholder="单位/学校"
                               onkeyup="autoComplete.start(event)">
                        <label for="user_org">单位/学校</label>
                        <div class="auto_hidden" style="height: auto;" id="auto">
                    </div>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control" id="password" name="password" placeholder="密码"
                               required>
                        <label for="password" id="password_label">密码</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control" id="password2" name="password2" placeholder="确认密码"
                               aria-describedby="pwdFeedback" required onkeyup="checkPWD()">
                        <label for="password2" id="password2_label">确认密码</label>
                        <div id="pwdFeedback" class="invalid-feedback">
                            两次输入的密码不同
                        </div>
                    </div>
                    <br/>
                    <div style="text-align: center">
                        {#                    {% if user.is_superuser == 1 %}#}
                        <button type="submit" class="btn btn-success">新增管理员</button>
                        {#                    {% endif %}#}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/adminuser/statistics.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    注册
{% endblock %}
{% block content %}
    <script>
        function get_not_clockin_rank() {
            var inputValue = []
            $.getJSON("not_clockin_rank", function (rank) {
                console.log(rank)
                rank.data.sort((a, b) => {
                    return b.cnt - a.cnt
                })
                var cnt = 0
                var realname, stunum, email, phone
                $('#rank').children().remove()
                $.each(rank.data, function (k, v) {
                    cnt++
                    console.log(v)
                    console.log(v['user']['user_name'])
                    if(v['user']['realname'] != null){
                        realname = v['user']['realname']
                    }else {
                        realname = '暂无绑定'
                    }
                    if(v['user']['user_bind_num'] != null){
                        stunum = v['user']['user_bind_num']
                    }else {
                        stunum = '暂无绑定'
                    }
                    if(v['user']['email'] != null){
                        email = v['user']['email']
                    }else {
                        email = '暂无绑定'
                    }
                    if(v['user']['phone'] != null){
                        phone = v['user']['phone']
                    }else {
                        phone = '暂无绑定'
                    }
                    $('#rank').append('<tr>'+
                        '<th scope="row">'+cnt+'</th>'+
                        '<td>'+realname+'</td>'+
                        '<td>'+stunum+'</td>'+
                        '<td>'+email+'</td>'+
                        '<td>'+phone+'</td>'+
                        '<td>'+v['cnt']+'</td>'+
                    '</tr>')
                })
            })
        }
    </script>
    <div class="container">
        <nav>
            <div class="nav nav-tabs border-0" id="nav-tab" role="tablist" style="position: relative;left: 32%">
                <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home"
                        type="button" role="tab" aria-controls="nav-home" aria-selected="true" style="color: black">
                    日打卡情况
                </button>
                <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile"
                        type="button" role="tab" aria-controls="nav-profile" aria-selected="false"
                        style="color: black">周打卡情况
                </button>
                <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact"
                        type="button" role="tab" aria-controls="nav-contact" aria-selected="false"
                        style="color: black">月打卡情况
                </button>
                <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-rank"
                        type="button" role="tab" aria-controls="nav-contact" aria-selected="false"
                        onclick="get_not_clockin_rank()"
                        style="color: black">打卡被提醒排行
                </button>
            </div>
        </nav>
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab"
                 style="position: relative;left: 16%">
                <iframe frameborder="0" src="{% url 'adminuser:statistics' %}?type=day" width="100%"
                        height="700"></iframe>
            </div>
            <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab"
                 style="position: relative;left: 16%">
                <iframe frameborder="0" src="{% url 'adminuser:statistics' %}?type=week" width="100%"
                        height="700"></iframe>
            </div>
            <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab"
                 style="position: relative;left: 16%">
                <iframe frameborder="0" src="{% url 'adminuser:statistics' %}?type=month" width="100%"
                        height="700"></iframe>
            </div>
            <div class="tab-pane fade" id="nav-rank" role="tabpanel" aria-labelledby="nav-contact-tab"
                 style="position: relative;">
                <br/>
                <a href="{% url 'adminuser:export_excel' %}" class="link-success">导出Excel</a>
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th scope="col">排行</th>
                        <th scope="col">姓名</th>
                        <th scope="col">学号</th>
                        <th scope="col">邮箱</th>
                        <th scope="col">手机</th>
                        <th scope="col">本月未打卡次数</th>
                    </tr>
                    </thead>
                    <tbody id="rank">

                    </tbody>
                </table>

            </div>
        </div>
    </div>
{% endblock %}