djangoProject/urls.py
import notifications.urls
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

import login.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('clockin/', include('clockin.urls')),
    path('adminuser/', include('adminuser.urls')),
    re_path(r'^password_reset/', include('password_reset.urls')),
    path('inbox/notifications', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('captcha', include('captcha.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = login.views.page_not_found_error
handler500 = login.views.page_error

login/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *
from . import views

app_name = 'login'

urlpatterns = [
    path('index/', views.index, name="index"),
    path("register/", views.register, name="register"),
    path('user_detail/', views.user_detail, name="user_detail"),
    path('user_update/', views.user_update, name="user_update"),
    path('user_login/', views.user_login, name="user_login"),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('user_delete/<str:user_uuid>', views.user_delete, name='user_delete'),
    re_path('^user_update/get_all_org/', views.get_all_org, name='get_all_org'),
    path('is_have_email', views.is_have_email, name='is_have_email'),
    path('check_pwd', views.check_pwd, name='check_pwd'),
    path('user_login/pc_get_captcha', views.pc_get_captcha, name='pc_get_captcha'),
    path('register/pc_get_captcha', views.pc_get_captcha, name='pc_get_captcha'),
    path('page_not_found_error', views.page_not_found_error, name='page_not_found_error'),
    path('page_error', views.page_error, name='page_error')
]

notice/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views

app_name = 'notice'

urlpatterns = [
    # path('index/', views.index, name="index"),
    path('list/', views.NoticeListView.as_view(), name='list'),
    path('update', views.NoticeUpdateView.as_view(), name='update')
]

notice/models.py
from django.db import models

# Create your models here.

notice/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin


# 继承ListView展示未读通知，访问前必须登录
class NoticeListView(LoginRequiredMixin, ListView):
    context_object_name = 'notices'
    template_name = 'notice/notice.html'
    login_url = '/login/user_login/'

    # 返回未读通知
    def get_queryset(self):
        return self.request.user.notifications.unread()


class NoticeUpdateView(View):
    def get(self, request):
        notice_id = request.GET.get('notice_id')
        # 已读单条通知
        if notice_id:
            request.user.notifications.get(id=notice_id).mark_as_read()
            return redirect('clockin:daily_clockin')
        # 清空全部通知
        else:
            request.user.notifications.mark_all_as_read()
            return redirect('notice:list')

templates/notice/notice.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    通知
{% endblock title %}

{% block content %}
    <div class="container">
        <br/>
        {% if notices %}
            <div class="d-grid gap-2 col-4 mx-auto">
                <a href="{% url "notice:update" %}" class="btn alert-warning" role="button">清空所有通知</a>
            </div>

            <!-- 未读通知列表 -->
            <div class="row mt-2 ml-4">
                <ul class="list-group">
                    {% for notice in notices %}
                        <li class="list-group-item" id="notice_link">
                            <a href="{% url "notice:update" %}?notice_id={{ notice.id }}"
                               target="_blank">
                    <span style="color: #5897fb;">
                        {{ notice.actor }}
                    </span>
                                在 <span style="color: #01a252;">疫情健康打卡</span> {{ notice.verb }}。
                            </a>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ notice.timestamp|date:"Y年m月d日 H:i" }}
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% else %}
            <div class="d-grid gap-2 col-6 mx-auto" style="text-align: center">
                <span class="alert-dark" style="margin: auto">暂无通知</span>
                <img src="{% static 'img/empty.png' %}">
            </div>
        {% endif %}
    </div>

    <style>
        #notice_link a:link {
            color: black;
        }

        #notice_link a:visited {
            color: lightgrey;
        }
    </style>
{% endblock content %}