adminuser/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views

app_name = 'adminuser'

urlpatterns = [
    # path('index/', views.index, name="index"),
    path('register/', views.register, name='register'),
    path('login', views.admin_login, name='login'),
    path('update', views.admin_update, name='update'),
    path('navi_statistics', views.navi_statistics, name='navi_statistics'),
    path('statistics', views.statistics, name='statistics'),
    path('not_clockin_rank', views.not_clockin_rank, name='not_clockin_rank'),
    path('export_excel', views.export_excel, name='export_excel')
]

clockin/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views

app_name = 'clockin'

urlpatterns = [
    # path('index/', views.index, name="index"),
    path('clockin_history', views.clockin_history, name="clockin_history"),
    path('daily_clockin', views.daily_clockin, name="daily_clockin"),
    path('is_clockin', views.is_clockin, name="is_clockin"),
    path('get_selection_data/<str:type>/<int:code>', views.get_selection_data, name='get_selection_data'),
]

djangoProject/urls.py
import notifications.urls
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

import login.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('clockin/', include('clockin.urls')),
    path('adminuser/', include('adminuser.urls')),
    re_path(r'^password_reset/', include('password_reset.urls')),
    path('inbox/notifications', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('captcha', include('captcha.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = login.views.page_not_found_error
handler500 = login.views.page_error

login/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *
from . import views

app_name = 'login'

urlpatterns = [
    path('index/', views.index, name="index"),
    path("register/", views.register, name="register"),
    path('user_detail/', views.user_detail, name="user_detail"),
    path('user_update/', views.user_update, name="user_update"),
    path('user_login/', views.user_login, name="user_login"),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('user_delete/<str:user_uuid>', views.user_delete, name='user_delete'),
    re_path('^user_update/get_all_org/', views.get_all_org, name='get_all_org'),
    path('is_have_email', views.is_have_email, name='is_have_email'),
    path('check_pwd', views.check_pwd, name='check_pwd'),
    path('user_login/pc_get_captcha', views.pc_get_captcha, name='pc_get_captcha'),
    path('register/pc_get_captcha', views.pc_get_captcha, name='pc_get_captcha'),
    path('page_not_found_error', views.page_not_found_error, name='page_not_found_error'),
    path('page_error', views.page_error, name='page_error')
]

notice/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views

app_name = 'notice'

urlpatterns = [
    # path('index/', views.index, name="index"),
    path('list/', views.NoticeListView.as_view(), name='list'),
    path('update', views.NoticeUpdateView.as_view(), name='update')
]

templates/base.html
{% load static %}
{% load filter %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    {#    <link type="text/css" rel="stylesheet" href="{% static 'css/containerImg.css' %}">#}
    <link type="text/css" rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <script src="{% static 'jquery/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    <script>
        $(document).ready(function () {
            $('#load').attr('style', 'display:none')
        })
    </script>
</head>
<style>
    body {
        background: url("{% static 'img/container-bg.jpg' %}") no-repeat fixed;
        background-size: contain;
    }
</style>
<body>
<!-- 引入导航栏 -->
{% include 'header.html' %}
<div class="d-flex justify-content-center" style="position: absolute;top: 50%;left: 50%">
    <div class="spinner-border" role="status" id="load">
        <span class="visually-hidden">Loading...</span>
    </div>
</div>
<!-- 预留具体页面的位置 -->
{% block content %}
{% endblock content %}
<!-- 引入注脚 -->
{% include 'footer.html' %}
{#<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>#}
<script src="{% static 'layer/layer.js' %}"></script>
{% block script %}{% endblock script %}
</body>

</html>

templates/chart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ data|safe }}
</body>
</html>

templates/footer.html
{% load static %}
<div>
    <br/><br/><br/>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">
            Copyright &copy; 陈柏宇 2112114536 2022
        </p>
    </div>
</footer>

templates/header.html
{% load notifications_tags %}
{% notifications_unread as unread_count %}


<script>
    //判断此用户今日是否已经打卡
    function isClockIn() {
        $.ajax({
            url: '{% url 'clockin:is_clockin' %}',
            type: 'get',
            success: function (msg) {
                json = eval("(" + msg + ")")
                if (json.result == "False") {
                    alert("今日已打卡")
                } else if (json.result == "True") {
                    window.location.href = "{% url 'clockin:daily_clockin' %}"
                } else if (json.result == "Org") {
                    alert("请先绑定所属单位/学校")
                }
            }
        })
    }
</script>
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
    <div class="container">

        <!-- 导航栏商标 -->
        <a class="navbar-brand" href="{% url 'login:index' %}">疫情健康打卡</a>

        <!-- 导航入口 -->
        <div>
            <ul class="navbar-nav">
                <!-- 条目 -->
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login:register' %}">没有账号？</a>
                    </li>
                {% elif user.is_superuser == 0 %}
                    <li class="nav-item">
                        <a class="nav-link" href="javascript:void(0)" onclick="isClockIn()">打卡</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'clockin:clockin_history' %}">打卡记录</a>
                    </li>
                {% elif request.session.admin_level != 1 %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'adminuser:navi_statistics' %}">统计数据</a>
                    </li>
                {% endif %}
                {% if user.is_superuser == 1 and request.session.admin_level == 1 %}
                    <a class="nav-link" href="{% url 'adminuser:register' %}">新增管理员</a>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle"
                           href="{% url 'login:user_detail' %}"
                           id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            <!-- 通知小红点 -->
                            {% if unread_count %}
                                <svg viewBox="0 0 8 8"
                                     width="8px"
                                     height="8px">
                                    <circle cx="4"
                                            cy="4"
                                            r="4"
                                            fill="#ff6b6b"
                                    ></circle>
                                </svg>
                            {% endif %}
                            {{ user.user_name }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <!-- 通知计数 -->
                            {% if not user.is_superuser %}
                            <a class="dropdown-item" href="{% url 'notice:list' %}">通知
                                {% if unread_count %}
                                    <span class="badge bg-danger">{{ unread_count }}</span>
                                {% endif %}
                            </a>
                            {% endif %}
                            <a class="dropdown-item" href="{% url "login:user_detail" %}">个人资料</a>
                            <a class="dropdown-item" href="{% url "login:user_logout" %}">退出登录</a>
                        </div>
                    </li>
                    <li class="navbar-brand">
                        <img class="rounded" src="{{ user.profile_photo.url }}" width="25" height="25">
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login:user_login' %}">登录</a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    注册
{% endblock %}
{% block content %}
<div class="container" style="background-image: {% static 'container-bg.jpg' %}">
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel" data-bs-interval="3000">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1" style="background-color: gray"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2" style="background-color: gray"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3" style="background-color: gray"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'img/pandemic.png' %}" class="d-block w-100" alt="疫情打卡">
        </div>
        <div class="carousel-item">
          <img src="{% static 'img/doctor.jpg' %}" class="d-block w-100" alt="医生">
        </div>
        <div class="carousel-item">
          <img src="{% static 'img/xmut.jpeg' %}" class="d-block w-100" alt="厦门理工">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev" style="color: darkgreen">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next" style="color: darkgreen">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
</div>
{% endblock content %}