adminuser/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views

app_name = 'adminuser'

urlpatterns = [
    # path('index/', views.index, name="index"),
    path('register/', views.register, name='register'),
    path('login', views.admin_login, name='login'),
    path('update', views.admin_update, name='update'),
    path('navi_statistics', views.navi_statistics, name='navi_statistics'),
    path('statistics', views.statistics, name='statistics'),
    path('not_clockin_rank', views.not_clockin_rank, name='not_clockin_rank'),
    path('export_excel', views.export_excel, name='export_excel')
]

djangoProject/urls.py
import notifications.urls
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

import login.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('clockin/', include('clockin.urls')),
    path('adminuser/', include('adminuser.urls')),
    re_path(r'^password_reset/', include('password_reset.urls')),
    path('inbox/notifications', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('captcha', include('captcha.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = login.views.page_not_found_error
handler500 = login.views.page_error

login/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *
from . import views

app_name = 'login'

urlpatterns = [
    path('index/', views.index, name="index"),
    path("register/", views.register, name="register"),
    path('user_detail/', views.user_detail, name="user_detail"),
    path('user_update/', views.user_update, name="user_update"),
    path('user_login/', views.user_login, name="user_login"),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('user_delete/<str:user_uuid>', views.user_delete, name='user_delete'),
    re_path('^user_update/get_all_org/', views.get_all_org, name='get_all_org'),
    path('is_have_email', views.is_have_email, name='is_have_email'),
    path('check_pwd', views.check_pwd, name='check_pwd'),
    path('user_login/pc_get_captcha', views.pc_get_captcha, name='pc_get_captcha'),
    path('register/pc_get_captcha', views.pc_get_captcha, name='pc_get_captcha'),
    path('page_not_found_error', views.page_not_found_error, name='page_not_found_error'),
    path('page_error', views.page_error, name='page_error')
]

login/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, UserManager
from PIL import Image


# Create your models here.

class Org(models.Model):
    org_id = models.CharField(max_length=255, blank=True, null=True)
    org_name = models.CharField(unique=True, max_length=255, blank=True, null=True)
    org_designate_location = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'org'


class User(AbstractBaseUser, PermissionsMixin):
    user_id = models.BigIntegerField(primary_key=True)
    user_name = models.CharField(max_length=255, blank=True, null=True)
    user_org = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True, unique=True)
    email = models.CharField(max_length=255, blank=True, null=True, unique=True)
    user_bind_num = models.CharField(max_length=50, blank=True, null=True)
    profile_photo = models.ImageField(upload_to='profile_photo/%Y%m%d/', max_length=255, blank=True, null=True,
                                      default='default.png')
    gender = models.IntegerField(blank=True, null=True)
    password = models.CharField(max_length=255, blank=True, null=True)
    user_uuid = models.CharField(max_length=255, blank=True, null=True)
    is_superuser = models.IntegerField(blank=True, null=True, default=0)
    realname = models.CharField(max_length=10, blank=True, null=True)

    last_login = None
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        managed = False
        db_table = 'user'

    def __str__(self):
        return self.email

    def save(self, *args, **kwargs):
        # 原有的save
        user = super(User, self).save(*args, **kwargs)
        # 固定宽度缩放
        if self.profile_photo and not kwargs.get('update_fields'):
            image = Image.open(self.profile_photo)
            (x, y) = image.size
            nx = 200
            ny = int(nx * (y / x))
            resized = image.resize((nx, ny), Image.ANTIALIAS)
            resized.save(self.profile_photo.path)

        return user


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("请填入邮箱！")
        if not password:
            raise ValueError("请填入密码!")
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        user = self._create_user(username=username, email=email, password=password)
        extra_fields.setdefault('is_superuser', True)

        # if extra_fields.get('is_staff') is not True:
        #     raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return user

login/forms.py
from django import forms
from .models import User


class UserLoginForm(forms.Form):
    email = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = User
        fields = ('email', 'password')


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('user_name', 'user_org', 'user_bind_num', 'phone', 'email', 'profile_photo', 'realname')


class UserRegisterForm(forms.ModelForm):
    # 复写 User 的密码
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ("password", "user_uuid", "email", 'user_name')

    # 对两次输入的密码是否一致进行检查
    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError("密码输入不一致,请重试。")

login/views.py
import json
import os

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.utils.datastructures import MultiValueDictKeyError
from geetest import GeetestLib

from .models import User, Org
from .forms import UserRegisterForm, UserUpdateForm, UserLoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.conf import settings
from django.contrib import messages
import uuid
from PIL import Image

# Create your views here.

pc_geetest_id = "f55c61e3970995968513fe70d2379a02"  # id
pc_geetest_key = "a64ef3f8ee1a0fcc5fc0ede61a443392"  # key


def pc_get_captcha(request):
    # 极验验证函数
    user_id = 'test'
    gt = GeetestLib(pc_geetest_id, pc_geetest_key)
    status = gt.pre_process(user_id)
    request.session[gt.GT_STATUS_SESSION_KEY] = status
    request.session["user_id"] = user_id
    response_str = gt.get_response_str()
    return HttpResponse(response_str)


def index(request):
    return render(request, "index.html")


def register(request):
    # 判断用户是否提交数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        user_register_form = UserRegisterForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            new_user.set_password(user_register_form.cleaned_data['password'])
            # 随机生成uuid
            new_user.user_uuid = uuid.uuid1()
            new_user.save()
            new_user = authenticate(email=new_user.email, password=user_register_form.cleaned_data['password'])
            login(request, new_user)
            request.session['user_uuid'] = new_user.user_uuid
            return redirect("login:index")
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    elif request.method == 'GET':
        # 创建表单类实例
        user_register_form = UserRegisterForm()
        # 赋值上下文
        context = {'user_form': user_register_form}
        # 返回模板
        return render(request, 'user/register.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


@login_required(login_url='/login/user_login/')
def user_detail(request):
    user = User.objects.get(user_uuid=request.session['user_uuid'])
    context = {"user": user}
    return render(request, "user/detail.html", context)


@login_required(login_url='/login/user_login/')
def user_update(request):
    user = User.objects.get(user_uuid=request.session['user_uuid'])
    photo = user.profile_photo.path
    # 判断用户是否提交数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        user_form = UserUpdateForm(request.POST, request.FILES, instance=user)
        # 判断提交的数据是否满足模型的要求
        if user_form.is_valid():
            user.user_name = request.POST['user_name']
            user.user_org = request.POST['user_org']
            if request.POST['phone'] == '' or request.POST['phone'] is None:
                user.phone = None
            else:
                user.phone = request.POST['phone']
            user.email = request.POST['email']
            user.user_bind_num = request.POST['user_bind_num']
            try:
                user.gender = request.POST['gender']
            except MultiValueDictKeyError:
                user.gender = 2
            if 'profile_photo' in request.FILES:
                if photo != settings.MEDIA_ROOT + "default.png":
                    os.remove(photo)
                user.profile_photo = request.FILES['profile_photo']
            user.save()
            if user.user_org is not None and user.user_org.strip() != '':
                request.session['location'] = Org.objects.filter(org_name=user.user_org).first().org_designate_location
            # 完成后返回到用户明细
            return redirect("login:user_detail")
        # 如果数据不合法，返回错误信息
        else:
            print(user_form.errors)
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    else:
        # 创建表单类实例
        user_update_form = UserUpdateForm()
        # 赋值上下文
        context = {'user': user, 'user_update_form': user_update_form}
        # 返回模板
        return render(request, 'user/update.html', context)


def user_login(request):
    if request.method == 'POST':
        user_form = UserLoginForm(data=request.POST)
        if user_form.is_valid():
            data = user_form.cleaned_data
            user = authenticate(email=data['email'], password=data['password'])
            if user:
                login(request, user)
                request.session['user_uuid'] = user.user_uuid
                request.session['location'] = Org.objects.filter(org_name=user.user_org).first().org_designate_location
                return redirect("login:index")
            else:
                messages.error(request, "账号或密码错误")
                return redirect("login:user_login")
        else:
            messages.error(request, "账号或密码错误")
            return redirect("login:user_login")
    elif request.method == 'GET':
        user_form = UserLoginForm()
        context = {'user_form': user_form}
        return render(request, 'user/login.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


@login_required(login_url='/login/user_login/')
def user_logout(request):
    logout(request)
    return redirect("login:index")


def get_all_org(request):
    org_list = Org.objects.all()
    org_list = serializers.serialize('json', org_list)
    return HttpResponse(org_list, content_type='application/json')


def is_have_email(request):
    val = request.POST.get('email')
    email = User.objects.filter(email=val).count()
    if email != 0:
        return HttpResponse(json.dumps(({'result': 'False'})))
    else:
        return HttpResponse(json.dumps(({'result': 'True'})))


def check_pwd(request):
    pwd1 = request.POST.get('pwd1')
    pwd2 = request.POST.get('pwd2')
    if str(pwd1) == str(pwd2):
        return HttpResponse(json.dumps(({'result': 'True'})))
    else:
        return HttpResponse(json.dumps(({'result': 'False'})))


@login_required(login_url='/login/user_login/')
def user_delete(request, user_uuid):
    if request.method == 'POST':
        user = User.objects.filter(user_uuid=user_uuid).first()
        # 验证登录用户、待删除用户是否相同
        if request.user == user:
            # 退出登录，删除数据
            logout(request)
            print(str(user))
            userUUID = str(user.user_uuid)
            print(userUUID)
            User.objects.get(user_uuid=userUUID).delete(using=User.objects.db)
            return redirect("login:index")
        else:
            return HttpResponse("你没有删除操作的权限。")
    else:
        return HttpResponse("仅接受post请求。")


def page_not_found_error(request, exception):
    return render(request, "index.html", context={'error': '访问有误:页面不存在'}, status=404)


def page_error(request):
    return render(request, "index.html", context={'error': '访问有误:服务器错误'}, status=500)

templates/user/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    用户详情
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <h1 class="col-12 mt-4 mb-4">
                {{ user.user_name }}
            </h1>
{#            <a href="#" class="page-link" onclick="user_delete()">注销本账户</a>#}
            {% if user.is_authenticated %}
                <form
                    style="display:none;"
                    id="user_delete"
                    action="{% url 'login:user_delete' user.user_uuid %}"
                    method="POST"
                >
                    {% csrf_token %}
                    <button type="submit">确认</button>
                </form>
                <script>
                    function user_delete() {
                        // 调用layer弹窗组件
                        layer.open({
                            title: "确认删除",
                            content: "确认删除用户资料吗？",
                            yes: function(index, layer) {
                                $('form#user_delete button').click();
                                layer.close(index);
                            },
                        })
                    }
                </script>
            {% endif %}
            <a href="{% url "login:user_update"%}" class="page-link">修改个人资料</a>
            <div class="col-12 alert alert-success">
                工号/学号：{% if user.user_bind_num is None or user.user_bind_num == '' %}暂未绑定{% else %}{{ user.user_bind_num }}{% endif %}
            </div>
            <div class="col-6">
                手机：{% if user.phone is None %}暂未绑定{% else %}{{ user.phone }}{% endif %}
            </div>
            <div class="col-6">
                邮箱：{{ user.email }}
            </div>
            <div class="col-6">
                单位/学校：{{ user.user_org }}
            </div>
            <div class="col-6">
                性别：{% if user.gender == 0 %}
                    女
                {% elif user.gender == 1 %}
                    男
                {% elif user.gender == 2 or user.gender is None %}
                    不想透露
                {% endif %}
            </div>
            {% if request.session.admin_level > 1 %}
            <div class="col-6">
                提醒打卡时间：{% if  request.session.strategy_time == '' %}暂未设置{% else %}{{ request.session.strategy_time }}{% endif %}
            </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/user/register.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    注册
{% endblock %}
{% block content %}

        <style>
        {#极验验证的样式#}
        #embed-captcha {
            width: 300px;
            margin: 0 auto;

        }

        .show {
            display: block;
        }

        .hide {
            display: none;
        }

        #notice {
            color: red;
        }
    </style>

    <script src="{% static 'js/gt.js' %}"></script>

    <script>
        //极验验证码
        var handlerEmbed = function (captchaObj) {
            $("#embed-submit").click(function (e) {
                var validate = captchaObj.getValidate();
                if (!validate) {
                    $("#notice")[0].className = "show";
                    setTimeout(function () {
                        $("#notice")[0].className = "hide";
                    }, 2000);
                    e.preventDefault();
                }
            });
            // 将验证码加到id为captcha的元素里，同时会有三个input的值：geetest_challenge, geetest_validate, geetest_seccode
            captchaObj.appendTo("#embed-captcha");
            captchaObj.onReady(function () {
                $("#wait")[0].className = "hide";
            });
        };
        $.ajax({
            // 获取id，challenge，success（是否启用failback）
            url: "pc_get_captcha?t=" + (new Date()).getTime(), // 加随机数防止缓存
            type: "get",
            dataType: "json",
            success: function (data) {
                // 参数1：配置参数
                // 参数2：回调，回调的第一个参数验证码对象
                initGeetest({
                    gt: data.gt,
                    challenge: data.challenge,
                    product: "embed",
                    offline: !data.success // 表示用户后台检测极验服务器是否宕机
                }, handlerEmbed);
            }
        });
    </script>

    <script>
        //判断是否重复邮箱
        function isHaveEmail() {
            $.ajax({
                url: '{% url 'login:is_have_email' %}',
                type: 'POST',
                data: {'email': $('#email').val()},
                dataType: 'json',
                success: function (msg) {
                    json = eval(msg)
                    if (json.result == "False") {
                        $('#email').addClass('is-invalid')
                    } else {
                        $('#email').removeClass('is-invalid')
                    }
                }
            })
        }

        function checkPWD() {
            $.ajax({
                url: '{% url 'login:check_pwd' %}',
                type: 'POST',
                data: {'pwd1': $('#password').val(), 'pwd2': $('#password2').val()},
                dataType: 'json',
                success: function (msg) {
                    json = eval(msg)
                    if (json.result == "False") {
                        $('#password').addClass('is-invalid')
                        $('#password2').addClass('is-invalid')
                    } else {
                        $('#password').removeClass('is-invalid')
                        $('#password2').removeClass('is-invalid')
                    }
                }
            })
        }
    </script>
    <div class="container">
        <div class="row card border-0" style="background: transparent">
            <div class="col-4 card-body m-auto">
                <br/>
                <form method="post" action=".">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="user_name" name="user_name" placeholder="用户名"
                               required>
                        <label for="user_name">用户名</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com"
                               aria-describedby="emailFeedback" required onkeyup="isHaveEmail()">
                        <label for="email" id="email_label">邮箱</label>
                        <div id="emailFeedback" class="invalid-feedback">
                            该邮箱已被注册
                        </div>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control" id="password" name="password" placeholder="密码"
                               required>
                        <label for="password" id="password_label">密码</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control" id="password2" name="password2" placeholder="确认密码"
                               aria-describedby="pwdFeedback" required onkeyup="checkPWD()">
                        <label for="password2" id="password2_label">确认密码</label>
                        <div id="pwdFeedback" class="invalid-feedback">
                            两次输入的密码不同
                        </div>
                    </div>
                    {# 极验验证 #}
                    <div id="embed-captcha"></div>
                    <div style="text-align: center">
                        <div class="spinner-border text-primary" id="wait" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                    </div>
                    <p id="notice" class="hide" style="text-align: center">请先验证验证码</p>
                    <br/>
                    <div style="text-align: center">
                        <button type="submit" class="btn btn-success" id="embed-submit">注册</button>
                    </div>
                    <br/>
                    <div class="alert alert-secondary text-center" role="alert">
                        忘记密码？<a href="{% url 'password_reset_recover' %}" class="alert-link">点我重制密码</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/user/update.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    更新个人资料
{% endblock %}
{% block content %}

    <link href="{% static 'css/IntelliSense.css' %}" type="text/css" rel="stylesheet"/>
    <link href="{% static 'css/cropper.min.css' %}" type="text/css" rel="stylesheet"/>
    <script src="{% static 'js/IntelliSense.js' %}"></script>
    <script src="{% static 'js/cropper.min.js' %}"></script>
    {# 单位/学校智能输入提示 #}
    <script>
        $(document).ready(function () {
            //$('#user_org').val(api);
            createApi();
        });

        var autoComplete;

        function createApi() {
            var inputValue = []
            $.getJSON("get_all_org", function (org) {
                $.each(org, function (k, v) {
                    inputValue.push(v['fields']['org_name'])
                })
            })

            if (!autoComplete) {
                autoComplete = new AutoComplete('user_org', 'auto', inputValue);//第一个参数是输入框id，第二个是下拉显示的id，第三个是获取的全部数据。
            }
            $('#user_org').blur(function () {//点击下拉选项得到获取值
                //alert($('#user_org').val());点击获取选择的值。
            });
        }
    </script>
    <div class="container">
        <div class="row card border-0" style="background: transparent">
            <div class="col-4 card-body m-auto">
                <br/>

                <form method="post"
                        {% if user.is_superuser == 0 %}
                      action="{% url 'login:user_update' %}"
                        {% else %}
                      action="{% url 'adminuser:update' %}"
                        {% endif %}
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    {% if user.profile_photo %}
                        <div class="text-center">
                            <img src="{{ user.profile_photo.url }}"
                                 class="rounded">
                        </div>
                    {% else %}
                        <h5 class="col-md-4">暂无头像</h5>
                    {% endif %}
                    <br/><br/>
                    <div class="mb-3">
                        <input type="file" class="form-control" aria-label="file example" name="profile_photo"
                               id="profile_photo">
                    </div>

                    <br/><br/>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="user_name" name="user_name" placeholder="用户名"
                               {% if user.user_name is not None %}value="{{ user.user_name }}"{% endif %}>
                        <label for="user_name">用户名</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="realname" name="realname" placeholder="用户名"
                               {% if user.realname is not None %}value="{{ user.realname }}"{% endif %}>
                        <label for="user_name">真实姓名</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="user_org" name="user_org" autocomplete="off"
                               placeholder="所属单位/学校"
                               onkeyup="autoComplete.start(event)" {% if user.user_org is not None %}
                               value="{{ user.user_org }}"{% endif %}>
                        <label for="user_org">所属单位/学校</label>
                        <div class="auto_hidden" style="height: auto;" id="auto">
                        </div>

                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="phone" name="phone" placeholder="手机号"
                                {% if user.phone is not None %}
                               value="{{ user.phone }}"{% endif %}>
                        <label for="phone">手机号</label>
                    </div>
                    <div class="form-floating mb-3">

                        <input type="email" class="form-control" id="email" name="email" placeholder="邮箱"
                                {% if user.email is not None %}
                               value="{{ user.email }}"{% endif %}>
                        <label for="email">邮箱</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="user_bind_num" name="user_bind_num"
                               placeholder="工号/学号"
                                {% if user.user_bind_num is not None %} value="{{ user.user_bind_num }}"{% endif %}>
                        <label for="user_bind_num">工号/学号</label>
                    </div>
                    <div class="form-group text-center">
                        <label for="gender">性别</label>
                        女<input type="radio" class="radio" id="gender" name="gender" value="0"
                                {% if user.gender == 0 %}checked="checked"{% endif %}>
                        男<input type="radio" class="radio" id="gender" name="gender" value="1"
                                {% if user.gender == 1 %}checked="checked"{% endif %}>
                        不想透露<input type="radio" class="radio" id="gender" name="gender" value="2"
                                   {% if user.gender == 2 %}checked="checked"{% endif %}>
                    </div>
                    {% if request.session.admin_level > 1 %}
                        <div class="form-floating mb-3">
                            <input type="time" class="form-control" id="strategy_time" name="strategy_time" placeholder="00:00"
                                    {% if request.session.strategy_time != '' %}
                                   value="{{ request.session.strategy_time }}"{% endif %}>
                            <label for="strategy_time">提醒打卡时间</label>
                        </div>
                    {% endif %}
                    <br/>
                    <div style="text-align: center">
                        <button type="submit" class="btn btn-success">更新个人资料</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}